### ISSUE TITLE
Client/Server sync Issues with vanilla switch mechanics

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft#390]
Wrong textures shown when switching Railcraft Tracks with vanilla levers.
![2014-11-17_16 55 08](https://cloud.githubusercontent.com/assets/7806504/5080846/cee27244-6e7a-11e4-998d-c3a50fe00a8d.png)
![2014-11-17_16 55 17](https://cloud.githubusercontent.com/assets/7806504/5080847/cee48106-6e7a-11e4-9041-288c7d43e730.png)
![2014-11-17_16 55 38](https://cloud.githubusercontent.com/assets/7806504/5080848/cee9ab68-6e7a-11e4-88bf-0f06cb4a3145.png)
![2014-11-17_16 55 49](https://cloud.githubusercontent.com/assets/7806504/5080849/ceef5720-6e7a-11e4-993b-ae0adf94fd57.png)
After few seconds it will change to normal.

**Comment by CovertJaguar** [comment]
This is probably fixed by https://github.com/MinecraftForge/MinecraftForge/pull/1627 and a11ab388f6bf7516eeb3112ae13b30658c19726b.

Closing.

**Comment by liach** [comment]
Bug still there.
![2015-01-09_16 29 26](https://cloud.githubusercontent.com/assets/7806504/5689629/f70ad01e-981d-11e4-81bf-c853fc843ce0.png)
Reopen requested.

**Comment by CovertJaguar** [comment]
@liach Commit https://github.com/CovertJaguar/Railcraft/commit/a11ab388f6bf7516eeb3112ae13b30658c19726b is also required to see any benefit.

**Comment by liach** [comment]
Really fixed after build and try. Thanks!
