### ISSUE TITLE
Crash with newest forge 1356

### ISSUE THREAD

**Issue by Headhunter14** [CovertJaguar/Railcraft#574]
Due to changes in forge, railcraft no longer works and crashes instead ( fluid registry and fluids related )
Crash report:
http://paste.ee/p/q34su

**Comment by Vexatos** [comment]
It's probably a bug in Forge, see https://github.com/MinecraftForge/MinecraftForge/pull/1775.

**Comment by Headhunter14** [comment]
ah i see.

**Comment by TheJulianJES** [comment]
Not a forge bug. @CovertJaguar a quick fix would be nice :)

**Comment by CovertJaguar** [comment]
Looks like a Forge bug to me. And is fixed by 1358.

**Comment by TheJulianJES** [comment]
@CovertJaguar It's not fixed for me, I upgraded to the latest forge version and it's crashing when going into a steam engine.

**Comment by CovertJaguar** [comment]
Yes, that's not this error though.

**Comment by TheJulianJES** [comment]
@CovertJaguar Okay, I'm sorry :)
